### ISSUE TITLE
[Feature Request] Particle sensor integration (HPMA115S0)

### ISSUE THREAD

**Issue by tom1422** [hugokernel/esphome-weather-station#1]
Hello,
Firstly I would like to say thank you for making this. It integrates much better with my Home Assistant installation and I haven't noticed any issues so far (expecting it to be far better than their original one in the long term). One question I have is the ability for a particle sensor to be linked. This would be really great. I am using the HPMA115S0 dust sensor and I would be happy to test any updates to see if they work and help fix bugs. Please let me know on your thoughts or if this would even work.
Kind regards,
Tom.

**Comment by hugokernel** [comment]
Hi,

I think its integration would be very simple because this sensor sends its data via UART.

Unfortunately, I do not have this sensor so, I cannot test it, I invite you to consult the examples of the project https://github.com/felixgalindo/HPMA115S0 and the ESPHome UART page https://esphome.io/components/uart.html.

I will take your feedback to integrate this later.

HPMA115S0 information:
* Product page: https://sensing.honeywell.com/hpma115s0-xxx-particulate-matter-sensors
* Datasheet: https://sensing.honeywell.com/honeywell-sensing-particulate-hpm-series-datasheet-32322550.pdf

**Comment by tom1422** [comment]
Hello,
I have created a first test build which uses a custom component in esphome. I will monitor it over a few days to test its reliability then post it here once i clean it up a little.

**Comment by tom1422** [comment]
I have uploaded the code to my github here:
[https://github.com/Wumfie/ESPHome-HPMA115S0-Sensor-Component](https://github.com/Wumfie/ESPHome-HPMA115S0-Sensor-Component)
Unfortunately, i couldn't get the yaml uart to work so instead I made a custom component. It has been working reliably for about 24 hours now but I welcome any improvements to the code.

**Comment by aerodolphin** [comment]
Can you tell if it's working? \<\<\<I would like to buy the sensors.

**Comment by tom1422** [comment]
Yeah its working fine. It might be worth getting one of the official ones listed here instead:
[https://esphome.io/index.html#air-quality](https://esphome.io/index.html#air-quality)
So it will be compatible out of the box.
