### ISSUE TITLE
Wind speed GPIO38 doesn't have INPUT_PULLUP

### ISSUE THREAD

**Issue by sermayoral** [hugokernel/esphome-weather-station#4]
Hi friend. I have seen your project. It's amazing and thank you for sharing it. There is a thing that is wrong:

```
  - platform: pulse_counter
    pin:
      number: GPIO38
      mode: INPUT_PULLUP
```

According to the esp32 specifications:

_GPIOs 34 to 39 are GPIs – input only pins. These pins don’t have internal pull-up or pull-down resistors. They can’t be used as outputs, so use these pins only as inputs:_

More recent ESPHome versions tells you as well:

![imagen](https://user-images.githubusercontent.com/30116095/143684485-d7afd3b0-e5ab-4daa-825e-6186dd9e1a06.png)

I hope it can help you :-)

I would like to ask you a doubt. I've got a WH-SP-WS01 anemometer. This one: https://a.aliexpress.com/_uAcawc

Do you think your calibration will be valid to me? Or i should calibrate it? Because it is a tedious process and I am not an expert on this subject.

Thank you very much!!

**Comment by hugokernel** [comment]
Hi,

Sorry for the lag, I don't have much time right now, about GPIO, I have to take a look.

> Do you think your calibration will be valid to me? Or i should calibrate it? Because it is a tedious process and I am not an expert on this subject.

Yes, I think it's the same.

**Comment by sermayoral** [comment]
Thank you very much ☺️

**Comment by tom1422** [comment]
I have this issue as well. Not sure if it makes any difference though. I decided to change the Rain Meter and Wind Speed pins to GPIO 33 and GPIO 32 (on ADC1 because ADC2 apparently interferes with wifi). 
This allows me to use input pull-up again as apparently pin 34 to 39 cannot be set as output, which is counter intuitive considering they are labelled as "GPIO".
Unfortunately, it means you have to ditch the Lora module (which i don't think they finished integrating) but it also makes it easier to connect it as the socket is already soldered. (D1 and D2 for the RFM95)
Just tried it and it made no difference (to using just using IO35 and no pullup). I will check with scope to double check.
Just checked with a scope and its reading the exact same values. Not sure if there's much point in changing the pins then. 
Although I have been receiving very low wind-speed values since putting it up. I might buy a professional meter an put it beside the weather station to calibrate it to get better constants.

**Comment by hugokernel** [comment]
Fixed and README updated.
